name: Sync Pinterest RSS

on:
  schedule:
    - cron: "0 6 * * *"   # daily at 6am UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Fetch Pinterest Board RSS
        run: |
          curl -L "https://www.pinterest.com/codychukwuebuka/my-visual-journal-cody-chukwuebuka/feed.rss" -o feed.xml

      - name: Convert RSS to JSON
        run: |
          node <<'EOF'
          const fs = require("fs");
          const xml = fs.readFileSync("feed.xml", "utf8");

          const items = [...xml.matchAll(/<item>([\s\S]*?)<\/item>/g)]
            .slice(0, 8)
            .map(match => {
              const block = match[1];

              const title =
                (block.match(/<title><!\[CDATA\[(.*?)\]\]><\/title>/) ||
                 block.match(/<title>(.*?)<\/title>/) ||
                 [])[1];

              const link = (block.match(/<link>(.*?)<\/link>/) || [])[1];
              const img = (block.match(/<img src="(https:\/\/i\.pinimg\.com\/[^"]+)"/) || [])[1];

              if (!img || !link) return null;

              return {
                title: title || "Pinterest Pin",
                image: img,
                link
              };
            })
            .filter(Boolean);

          fs.writeFileSync(
            "pinterest.json",
            JSON.stringify(items, null, 2)
          );
          EOF

      - name: Commit updated Pinterest data
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add pinterest.json
          git commit -m "Auto-sync Pinterest board" || echo "No changes"
          git push origin main
